[pytest]
norecursedirs = build docs/_build *.egg .tox *.venv
addopts =
    # Shows a line for every test
    # You probably want to turn this off if you use pytest-sugar.
    # Or you can keep it and run `py.test -q`.
    # --verbose

    # Shorter tracebacks are sometimes easier to read
    --tb=short

    # Turn on --capture to have brief, less noisy output.
    # You will only see output if the test fails.
    # Use --capture no (same as -s) if you want to see it all or have problems
    # debugging.
    # --capture=fd
    # --capture=no

    # Show extra test summary info as specified by chars (f)ailed, (E)error, (s)skipped, (x)failed, (X)passed.
    -rfEsxX

    # Output test results to junit.xml for Jenkins to consume
    # --junitxml=junit.xml

    # Measure code coverage
    # --cov=mrjob
    # --cov-report=xml
    # --cov-report=term-missing
