# Copyright 2009-2011 Yelp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utility functions for compatibility with different version of hadoop."""

# keep a mapping for all the names of old/new jobconf env variables
# http://hadoop.apache.org/mapreduce/docs/current/mapred-default.html

# lists alternative names for jobconf variables
# full listing thanks to translation table in http://pydoop.sourceforge.net/docs/examples/intro.html#hadoop-0-21-0-notes
jobconf_map = {
    "mapreduce.jobtracker.jobhistory.location": {'0.21': "mapreduce.jobtracker.jobhistory.location", '0.18': "hadoop.job.history.location"},
    "hadoop.job.history.location": {'0.21': "mapreduce.jobtracker.jobhistory.location", '0.18': "hadoop.job.history.location"},
    "mapreduce.job.userhistorylocation": {'0.21': "mapreduce.job.userhistorylocation", '0.18': "hadoop.job.history.user.location"},
    "hadoop.job.history.user.location": {'0.21': "mapreduce.job.userhistorylocation", '0.18': "hadoop.job.history.user.location"},
    "mapreduce.tasktracker.net.static.resolutions": {'0.21': "mapreduce.tasktracker.net.static.resolutions", '0.18': "hadoop.net.static.resolutions"},
    "hadoop.net.static.resolutions": {'0.21': "mapreduce.tasktracker.net.static.resolutions", '0.18': "hadoop.net.static.resolutions"},
    "mapreduce.pipes.commandfile.preserve": {'0.21': "mapreduce.pipes.commandfile.preserve", '0.18': "hadoop.pipes.command-file.keep"},
    "hadoop.pipes.command-file.keep": {'0.21': "mapreduce.pipes.commandfile.preserve", '0.18': "hadoop.pipes.command-file.keep"},
    "mapreduce.pipes.executable": {'0.21': "mapreduce.pipes.executable", '0.18': "hadoop.pipes.executable"},
    "hadoop.pipes.executable": {'0.21': "mapreduce.pipes.executable", '0.18': "hadoop.pipes.executable"},
    "mapreduce.pipes.executable.interpretor": {'0.21': "mapreduce.pipes.executable.interpretor", '0.18': "hadoop.pipes.executable.interpretor"},
    "hadoop.pipes.executable.interpretor": {'0.21': "mapreduce.pipes.executable.interpretor", '0.18': "hadoop.pipes.executable.interpretor"},
    "mapreduce.pipes.isjavamapper": {'0.21': "mapreduce.pipes.isjavamapper", '0.18': "hadoop.pipes.java.mapper"},
    "hadoop.pipes.java.mapper": {'0.21': "mapreduce.pipes.isjavamapper", '0.18': "hadoop.pipes.java.mapper"},
    "mapreduce.pipes.isjavarecordreader": {'0.21': "mapreduce.pipes.isjavarecordreader", '0.18': "hadoop.pipes.java.recordreader"},
    "hadoop.pipes.java.recordreader": {'0.21': "mapreduce.pipes.isjavarecordreader", '0.18': "hadoop.pipes.java.recordreader"},
    "mapreduce.pipes.isjavarecordwriter": {'0.21': "mapreduce.pipes.isjavarecordwriter", '0.18': "hadoop.pipes.java.recordwriter"},
    "hadoop.pipes.java.recordwriter": {'0.21': "mapreduce.pipes.isjavarecordwriter", '0.18': "hadoop.pipes.java.recordwriter"},
    "mapreduce.pipes.isjavareducer": {'0.21': "mapreduce.pipes.isjavareducer", '0.18': "hadoop.pipes.java.reducer"},
    "hadoop.pipes.java.reducer": {'0.21': "mapreduce.pipes.isjavareducer", '0.18': "hadoop.pipes.java.reducer"},
    "mapreduce.pipes.partitioner": {'0.21': "mapreduce.pipes.partitioner", '0.18': "hadoop.pipes.partitioner"},
    "hadoop.pipes.partitioner": {'0.21': "mapreduce.pipes.partitioner", '0.18': "hadoop.pipes.partitioner"},
    "mapreduce.task.io.sort.factor": {'0.21': "mapreduce.task.io.sort.factor", '0.18': "io.sort.factor"},
    "io.sort.factor": {'0.21': "mapreduce.task.io.sort.factor", '0.18': "io.sort.factor"},
    "mapreduce.task.io.sort.mb": {'0.21': "mapreduce.task.io.sort.mb", '0.18': "io.sort.mb"},
    "io.sort.mb": {'0.21': "mapreduce.task.io.sort.mb", '0.18': "io.sort.mb"},
    "mapreduce.map.sort.spill.percent": {'0.21': "mapreduce.map.sort.spill.percent", '0.18': "io.sort.spill.percent"},
    "io.sort.spill.percent": {'0.21': "mapreduce.map.sort.spill.percent", '0.18': "io.sort.spill.percent"},
    "mapreduce.job.end-notification.url": {'0.21': "mapreduce.job.end-notification.url", '0.18': "job.end.notification.url"},
    "job.end.notification.url": {'0.21': "mapreduce.job.end-notification.url", '0.18': "job.end.notification.url"},
    "mapreduce.job.end-notification.retry.attempts": {'0.21': "mapreduce.job.end-notification.retry.attempts", '0.18': "job.end.retry.attempts"},
    "job.end.retry.attempts": {'0.21': "mapreduce.job.end-notification.retry.attempts", '0.18': "job.end.retry.attempts"},
    "mapreduce.job.end-notification.retry.interval": {'0.21': "mapreduce.job.end-notification.retry.interval", '0.18': "job.end.retry.interval"},
    "job.end.retry.interval": {'0.21': "mapreduce.job.end-notification.retry.interval", '0.18': "job.end.retry.interval"},
    "mapreduce.job.local.dir": {'0.21': "mapreduce.job.local.dir", '0.18': "job.local.dir"},
    "job.local.dir": {'0.21': "mapreduce.job.local.dir", '0.18': "job.local.dir"},
    "mapreduce.client.completion.pollinterval": {'0.21': "mapreduce.client.completion.pollinterval", '0.18': "jobclient.completion.poll.interval"},
    "jobclient.completion.poll.interval": {'0.21': "mapreduce.client.completion.pollinterval", '0.18': "jobclient.completion.poll.interval"},
    "mapreduce.client.output.filter": {'0.21': "mapreduce.client.output.filter", '0.18': "jobclient.output.filter"},
    "jobclient.output.filter": {'0.21': "mapreduce.client.output.filter", '0.18': "jobclient.output.filter"},
    "mapreduce.client.progressmonitor.pollinterval": {'0.21': "mapreduce.client.progressmonitor.pollinterval", '0.18': "jobclient.progress.monitor.poll.interval"},
    "jobclient.progress.monitor.poll.interval": {'0.21': "mapreduce.client.progressmonitor.pollinterval", '0.18': "jobclient.progress.monitor.poll.interval"},
    "mapreduce.task.files.preserve.failedtasks": {'0.21': "mapreduce.task.files.preserve.failedtasks", '0.18': "keep.failed.task.files"},
    "keep.failed.task.files": {'0.21': "mapreduce.task.files.preserve.failedtasks", '0.18': "keep.failed.task.files"},
    "mapreduce.task.files.preserve.filepattern": {'0.21': "mapreduce.task.files.preserve.filepattern", '0.18': "keep.task.files.pattern"},
    "keep.task.files.pattern": {'0.21': "mapreduce.task.files.preserve.filepattern", '0.18': "keep.task.files.pattern"},
    "mapreduce.input.keyvaluelinerecordreader.key.value.separator": {'0.21': "mapreduce.input.keyvaluelinerecordreader.key.value.separator", '0.18': "key.value.separator.in.input.line"},
    "key.value.separator.in.input.line": {'0.21': "mapreduce.input.keyvaluelinerecordreader.key.value.separator", '0.18': "key.value.separator.in.input.line"},
    "mapreduce.tasktracker.cache.local.size": {'0.21': "mapreduce.tasktracker.cache.local.size", '0.18': "local.cache.size"},
    "local.cache.size": {'0.21': "mapreduce.tasktracker.cache.local.size", '0.18': "local.cache.size"},
    "mapreduce.map.input.file": {'0.21': "mapreduce.map.input.file", '0.18': "map.input.file"},
    "map.input.file": {'0.21': "mapreduce.map.input.file", '0.18': "map.input.file"},
    "mapreduce.map.input.length": {'0.21': "mapreduce.map.input.length", '0.18': "map.input.length"},
    "map.input.length": {'0.21': "mapreduce.map.input.length", '0.18': "map.input.length"},
    "mapreduce.map.input.start": {'0.21': "mapreduce.map.input.start", '0.18': "map.input.start"},
    "map.input.start": {'0.21': "mapreduce.map.input.start", '0.18': "map.input.start"},
    "mapreduce.map.output.key.field.separator": {'0.21': "mapreduce.map.output.key.field.separator", '0.18': "map.output.key.field.separator"},
    "map.output.key.field.separator": {'0.21': "mapreduce.map.output.key.field.separator", '0.18': "map.output.key.field.separator"},
    "mapreduce.fieldsel.map.output.key.value.fields.spec": {'0.21': "mapreduce.fieldsel.map.output.key.value.fields.spec", '0.18': "map.output.key.value.fields.spec"},
    "map.output.key.value.fields.spec": {'0.21': "mapreduce.fieldsel.map.output.key.value.fields.spec", '0.18': "map.output.key.value.fields.spec"},
    "mapreduce.partition.binarypartitioner.left.offset": {'0.21': "mapreduce.partition.binarypartitioner.left.offset", '0.18': "mapred.binary.partitioner.left.offset"},
    "mapred.binary.partitioner.left.offset": {'0.21': "mapreduce.partition.binarypartitioner.left.offset", '0.18': "mapred.binary.partitioner.left.offset"},
    "mapreduce.partition.binarypartitioner.right.offset": {'0.21': "mapreduce.partition.binarypartitioner.right.offset", '0.18': "mapred.binary.partitioner.right.offset"},
    "mapred.binary.partitioner.right.offset": {'0.21': "mapreduce.partition.binarypartitioner.right.offset", '0.18': "mapred.binary.partitioner.right.offset"},
    "mapreduce.job.cache.archives": {'0.21': "mapreduce.job.cache.archives", '0.18': "mapred.cache.archives"},
    "mapred.cache.archives": {'0.21': "mapreduce.job.cache.archives", '0.18': "mapred.cache.archives"},
    "mapreduce.job.cache.archives.timestamps": {'0.21': "mapreduce.job.cache.archives.timestamps", '0.18': "mapred.cache.archives.timestamps"},
    "mapred.cache.archives.timestamps": {'0.21': "mapreduce.job.cache.archives.timestamps", '0.18': "mapred.cache.archives.timestamps"},
    "mapreduce.job.cache.files": {'0.21': "mapreduce.job.cache.files", '0.18': "mapred.cache.files"},
    "mapred.cache.files": {'0.21': "mapreduce.job.cache.files", '0.18': "mapred.cache.files"},
    "mapreduce.job.cache.files.timestamps": {'0.21': "mapreduce.job.cache.files.timestamps", '0.18': "mapred.cache.files.timestamps"},
    "mapred.cache.files.timestamps": {'0.21': "mapreduce.job.cache.files.timestamps", '0.18': "mapred.cache.files.timestamps"},
    "mapreduce.job.cache.local.archives": {'0.21': "mapreduce.job.cache.local.archives", '0.18': "mapred.cache.localArchives"},
    "mapred.cache.localArchives": {'0.21': "mapreduce.job.cache.local.archives", '0.18': "mapred.cache.localArchives"},
    "mapreduce.job.cache.local.files": {'0.21': "mapreduce.job.cache.local.files", '0.18': "mapred.cache.localFiles"},
    "mapred.cache.localFiles": {'0.21': "mapreduce.job.cache.local.files", '0.18': "mapred.cache.localFiles"},
    "mapreduce.task.tmp.dir": {'0.21': "mapreduce.task.tmp.dir", '0.18': "mapred.child.tmp"},
    "mapred.child.tmp": {'0.21': "mapreduce.task.tmp.dir", '0.18': "mapred.child.tmp"},
    "mapreduce.jobtracker.blacklist.average.threshold": {'0.21': "mapreduce.jobtracker.blacklist.average.threshold", '0.18': "mapred.cluster.average.blacklist.threshold"},
    "mapred.cluster.average.blacklist.threshold": {'0.21': "mapreduce.jobtracker.blacklist.average.threshold", '0.18': "mapred.cluster.average.blacklist.threshold"},
    "mapreduce.cluster.mapmemory.mb": {'0.21': "mapreduce.cluster.mapmemory.mb", '0.18': "mapred.cluster.map.memory.mb"},
    "mapred.cluster.map.memory.mb": {'0.21': "mapreduce.cluster.mapmemory.mb", '0.18': "mapred.cluster.map.memory.mb"},
    "mapreduce.jobtracker.maxmapmemory.mb": {'0.21': "mapreduce.jobtracker.maxmapmemory.mb", '0.18': "mapred.cluster.max.map.memory.mb"},
    "mapred.cluster.max.map.memory.mb": {'0.21': "mapreduce.jobtracker.maxmapmemory.mb", '0.18': "mapred.cluster.max.map.memory.mb"},
    "mapreduce.jobtracker.maxreducememory.mb": {'0.21': "mapreduce.jobtracker.maxreducememory.mb", '0.18': "mapred.cluster.max.reduce.memory.mb"},
    "mapred.cluster.max.reduce.memory.mb": {'0.21': "mapreduce.jobtracker.maxreducememory.mb", '0.18': "mapred.cluster.max.reduce.memory.mb"},
    "mapreduce.cluster.reducememory.mb": {'0.21': "mapreduce.cluster.reducememory.mb", '0.18': "mapred.cluster.reduce.memory.mb"},
    "mapred.cluster.reduce.memory.mb": {'0.21': "mapreduce.cluster.reducememory.mb", '0.18': "mapred.cluster.reduce.memory.mb"},
    "mapreduce.job.committer.setup.cleanup.needed": {'0.21': "mapreduce.job.committer.setup.cleanup.needed", '0.18': "mapred.committer.job.setup.cleanup.needed"},
    "mapred.committer.job.setup.cleanup.needed": {'0.21': "mapreduce.job.committer.setup.cleanup.needed", '0.18': "mapred.committer.job.setup.cleanup.needed"},
    "mapreduce.map.output.compress": {'0.21': "mapreduce.map.output.compress", '0.18': "mapred.compress.map.output"},
    "mapred.compress.map.output": {'0.21': "mapreduce.map.output.compress", '0.18': "mapred.compress.map.output"},
    "mapreduce.job.cache.symlink.create": {'0.21': "mapreduce.job.cache.symlink.create", '0.18': "mapred.create.symlink"},
    "mapred.create.symlink": {'0.21': "mapreduce.job.cache.symlink.create", '0.18': "mapred.create.symlink"},
    "mapreduce.fieldsel.data.field.separator": {'0.21': "mapreduce.fieldsel.data.field.separator", '0.18': "mapred.data.field.separator"},
    "mapred.data.field.separator": {'0.21': "mapreduce.fieldsel.data.field.separator", '0.18': "mapred.data.field.separator"},
    "mapreduce.task.debugout.lines": {'0.21': "mapreduce.task.debugout.lines", '0.18': "mapred.debug.out.lines"},
    "mapred.debug.out.lines": {'0.21': "mapreduce.task.debugout.lines", '0.18': "mapred.debug.out.lines"},
    "mapreduce.tasktracker.healthchecker.interval": {'0.21': "mapreduce.tasktracker.healthchecker.interval", '0.18': "mapred.healthChecker.interval"},
    "mapred.healthChecker.interval": {'0.21': "mapreduce.tasktracker.healthchecker.interval", '0.18': "mapred.healthChecker.interval"},
    "mapreduce.tasktracker.healthchecker.script.args": {'0.21': "mapreduce.tasktracker.healthchecker.script.args", '0.18': "mapred.healthChecker.script.args"},
    "mapred.healthChecker.script.args": {'0.21': "mapreduce.tasktracker.healthchecker.script.args", '0.18': "mapred.healthChecker.script.args"},
    "mapreduce.tasktracker.healthchecker.script.path": {'0.21': "mapreduce.tasktracker.healthchecker.script.path", '0.18': "mapred.healthChecker.script.path"},
    "mapred.healthChecker.script.path": {'0.21': "mapreduce.tasktracker.healthchecker.script.path", '0.18': "mapred.healthChecker.script.path"},
    "mapreduce.tasktracker.healthchecker.script.timeout": {'0.21': "mapreduce.tasktracker.healthchecker.script.timeout", '0.18': "mapred.healthChecker.script.timeout"},
    "mapred.healthChecker.script.timeout": {'0.21': "mapreduce.tasktracker.healthchecker.script.timeout", '0.18': "mapred.healthChecker.script.timeout"},
    "mapreduce.jobtracker.heartbeats.in.second": {'0.21': "mapreduce.jobtracker.heartbeats.in.second", '0.18': "mapred.heartbeats.in.second"},
    "mapred.heartbeats.in.second": {'0.21': "mapreduce.jobtracker.heartbeats.in.second", '0.18': "mapred.heartbeats.in.second"},
    "mapreduce.jobtracker.hosts.filename": {'0.21': "mapreduce.jobtracker.hosts.filename", '0.18': "mapred.hosts"},
    "mapred.hosts": {'0.21': "mapreduce.jobtracker.hosts.filename", '0.18': "mapred.hosts"},
    "mapreduce.jobtracker.hosts.exclude.filename": {'0.21': "mapreduce.jobtracker.hosts.exclude.filename", '0.18': "mapred.hosts.exclude"},
    "mapred.hosts.exclude": {'0.21': "mapreduce.jobtracker.hosts.exclude.filename", '0.18': "mapred.hosts.exclude"},
    "mapreduce.reduce.merge.inmem.threshold": {'0.21': "mapreduce.reduce.merge.inmem.threshold", '0.18': "mapred.inmem.merge.threshold"},
    "mapred.inmem.merge.threshold": {'0.21': "mapreduce.reduce.merge.inmem.threshold", '0.18': "mapred.inmem.merge.threshold"},
    "mapreduce.input.fileinputformat.inputdir": {'0.21': "mapreduce.input.fileinputformat.inputdir", '0.18': "mapred.input.dir"},
    "mapred.input.dir": {'0.21': "mapreduce.input.fileinputformat.inputdir", '0.18': "mapred.input.dir"},
    "mapreduce.input.multipleinputs.dir.formats": {'0.21': "mapreduce.input.multipleinputs.dir.formats", '0.18': "mapred.input.dir.formats"},
    "mapred.input.dir.formats": {'0.21': "mapreduce.input.multipleinputs.dir.formats", '0.18': "mapred.input.dir.formats"},
    "mapreduce.input.multipleinputs.dir.mappers": {'0.21': "mapreduce.input.multipleinputs.dir.mappers", '0.18': "mapred.input.dir.mappers"},
    "mapred.input.dir.mappers": {'0.21': "mapreduce.input.multipleinputs.dir.mappers", '0.18': "mapred.input.dir.mappers"},
    "mapreduce.input.pathFilter.class": {'0.21': "mapreduce.input.pathFilter.class", '0.18': "mapred.input.pathFilter.class"},
    "mapred.input.pathFilter.class": {'0.21': "mapreduce.input.pathFilter.class", '0.18': "mapred.input.pathFilter.class"},
    "mapreduce.job.jar": {'0.21': "mapreduce.job.jar", '0.18': "mapred.jar"},
    "mapred.jar": {'0.21': "mapreduce.job.jar", '0.18': "mapred.jar"},
    "mapreduce.job.classpath.archives": {'0.21': "mapreduce.job.classpath.archives", '0.18': "mapred.job.classpath.archives"},
    "mapred.job.classpath.archives": {'0.21': "mapreduce.job.classpath.archives", '0.18': "mapred.job.classpath.archives"},
    "mapreduce.job.classpath.files": {'0.21': "mapreduce.job.classpath.files", '0.18': "mapred.job.classpath.files"},
    "mapred.job.classpath.files": {'0.21': "mapreduce.job.classpath.files", '0.18': "mapred.job.classpath.files"},
    "mapreduce.job.id": {'0.21': "mapreduce.job.id", '0.18': "mapred.job.id"},
    "mapred.job.id": {'0.21': "mapreduce.job.id", '0.18': "mapred.job.id"},
    "mapreduce.map.memory.mb": {'0.21': "mapreduce.map.memory.mb", '0.18': "mapred.job.map.memory.mb"},
    "mapred.job.map.memory.mb": {'0.21': "mapreduce.map.memory.mb", '0.18': "mapred.job.map.memory.mb"},
    "mapreduce.job.name": {'0.21': "mapreduce.job.name", '0.18': "mapred.job.name"},
    "mapred.job.name": {'0.21': "mapreduce.job.name", '0.18': "mapred.job.name"},
    "mapreduce.job.priority": {'0.21': "mapreduce.job.priority", '0.18': "mapred.job.priority"},
    "mapred.job.priority": {'0.21': "mapreduce.job.priority", '0.18': "mapred.job.priority"},
    "mapreduce.job.queuename": {'0.21': "mapreduce.job.queuename", '0.18': "mapred.job.queue.name"},
    "mapred.job.queue.name": {'0.21': "mapreduce.job.queuename", '0.18': "mapred.job.queue.name"},
    "mapreduce.reduce.input.buffer.percent": {'0.21': "mapreduce.reduce.input.buffer.percent", '0.18': "mapred.job.reduce.input.buffer.percent"},
    "mapred.job.reduce.input.buffer.percent": {'0.21': "mapreduce.reduce.input.buffer.percent", '0.18': "mapred.job.reduce.input.buffer.percent"},
    "mapreduce.reduce.markreset.buffer.percent": {'0.21': "mapreduce.reduce.markreset.buffer.percent", '0.18': "mapred.job.reduce.markreset.buffer.percent"},
    "mapred.job.reduce.markreset.buffer.percent": {'0.21': "mapreduce.reduce.markreset.buffer.percent", '0.18': "mapred.job.reduce.markreset.buffer.percent"},
    "mapreduce.reduce.memory.mb": {'0.21': "mapreduce.reduce.memory.mb", '0.18': "mapred.job.reduce.memory.mb"},
    "mapred.job.reduce.memory.mb": {'0.21': "mapreduce.reduce.memory.mb", '0.18': "mapred.job.reduce.memory.mb"},
    "mapreduce.reduce.memory.totalbytes": {'0.21': "mapreduce.reduce.memory.totalbytes", '0.18': "mapred.job.reduce.total.mem.bytes"},
    "mapred.job.reduce.total.mem.bytes": {'0.21': "mapreduce.reduce.memory.totalbytes", '0.18': "mapred.job.reduce.total.mem.bytes"},
    "mapreduce.job.jvm.numtasks": {'0.21': "mapreduce.job.jvm.numtasks", '0.18': "mapred.job.reuse.jvm.num.tasks"},
    "mapred.job.reuse.jvm.num.tasks": {'0.21': "mapreduce.job.jvm.numtasks", '0.18': "mapred.job.reuse.jvm.num.tasks"},
    "mapreduce.reduce.shuffle.input.buffer.percent": {'0.21': "mapreduce.reduce.shuffle.input.buffer.percent", '0.18': "mapred.job.shuffle.input.buffer.percent"},
    "mapred.job.shuffle.input.buffer.percent": {'0.21': "mapreduce.reduce.shuffle.input.buffer.percent", '0.18': "mapred.job.shuffle.input.buffer.percent"},
    "mapreduce.reduce.shuffle.merge.percent": {'0.21': "mapreduce.reduce.shuffle.merge.percent", '0.18': "mapred.job.shuffle.merge.percent"},
    "mapred.job.shuffle.merge.percent": {'0.21': "mapreduce.reduce.shuffle.merge.percent", '0.18': "mapred.job.shuffle.merge.percent"},
    "mapreduce.jobtracker.address": {'0.21': "mapreduce.jobtracker.address", '0.18': "mapred.job.tracker"},
    "mapred.job.tracker": {'0.21': "mapreduce.jobtracker.address", '0.18': "mapred.job.tracker"},
    "mapreduce.jobtracker.handler.count": {'0.21': "mapreduce.jobtracker.handler.count", '0.18': "mapred.job.tracker.handler.count"},
    "mapred.job.tracker.handler.count": {'0.21': "mapreduce.jobtracker.handler.count", '0.18': "mapred.job.tracker.handler.count"},
    "mapreduce.jobtracker.http.address": {'0.21': "mapreduce.jobtracker.http.address", '0.18': "mapred.job.tracker.http.address"},
    "mapred.job.tracker.http.address": {'0.21': "mapreduce.jobtracker.http.address", '0.18': "mapred.job.tracker.http.address"},
    "mapreduce.jobtracker.jobhistory.lru.cache.size": {'0.21': "mapreduce.jobtracker.jobhistory.lru.cache.size", '0.18': "mapred.job.tracker.jobhistory.lru.cache.size"},
    "mapred.job.tracker.jobhistory.lru.cache.size": {'0.21': "mapreduce.jobtracker.jobhistory.lru.cache.size", '0.18': "mapred.job.tracker.jobhistory.lru.cache.size"},
    "mapreduce.jobtracker.persist.jobstatus.active": {'0.21': "mapreduce.jobtracker.persist.jobstatus.active", '0.18': "mapred.job.tracker.persist.jobstatus.active"},
    "mapred.job.tracker.persist.jobstatus.active": {'0.21': "mapreduce.jobtracker.persist.jobstatus.active", '0.18': "mapred.job.tracker.persist.jobstatus.active"},
    "mapreduce.jobtracker.persist.jobstatus.dir": {'0.21': "mapreduce.jobtracker.persist.jobstatus.dir", '0.18': "mapred.job.tracker.persist.jobstatus.dir"},
    "mapred.job.tracker.persist.jobstatus.dir": {'0.21': "mapreduce.jobtracker.persist.jobstatus.dir", '0.18': "mapred.job.tracker.persist.jobstatus.dir"},
    "mapreduce.jobtracker.persist.jobstatus.hours": {'0.21': "mapreduce.jobtracker.persist.jobstatus.hours", '0.18': "mapred.job.tracker.persist.jobstatus.hours"},
    "mapred.job.tracker.persist.jobstatus.hours": {'0.21': "mapreduce.jobtracker.persist.jobstatus.hours", '0.18': "mapred.job.tracker.persist.jobstatus.hours"},
    "mapreduce.jobtracker.retirejobs": {'0.21': "mapreduce.jobtracker.retirejobs", '0.18': "mapred.job.tracker.retire.jobs"},
    "mapred.job.tracker.retire.jobs": {'0.21': "mapreduce.jobtracker.retirejobs", '0.18': "mapred.job.tracker.retire.jobs"},
    "mapreduce.jobtracker.retiredjobs.cache.size": {'0.21': "mapreduce.jobtracker.retiredjobs.cache.size", '0.18': "mapred.job.tracker.retiredjobs.cache.size"},
    "mapred.job.tracker.retiredjobs.cache.size": {'0.21': "mapreduce.jobtracker.retiredjobs.cache.size", '0.18': "mapred.job.tracker.retiredjobs.cache.size"},
    "mapreduce.jobtracker.jobinit.threads": {'0.21': "mapreduce.jobtracker.jobinit.threads", '0.18': "mapred.jobinit.threads"},
    "mapred.jobinit.threads": {'0.21': "mapreduce.jobtracker.jobinit.threads", '0.18': "mapred.jobinit.threads"},
    "mapreduce.jobtracker.instrumentation": {'0.21': "mapreduce.jobtracker.instrumentation", '0.18': "mapred.jobtracker.instrumentation"},
    "mapred.jobtracker.instrumentation": {'0.21': "mapreduce.jobtracker.instrumentation", '0.18': "mapred.jobtracker.instrumentation"},
    "mapreduce.jobtracker.jobhistory.block.size": {'0.21': "mapreduce.jobtracker.jobhistory.block.size", '0.18': "mapred.jobtracker.job.history.block.size"},
    "mapred.jobtracker.job.history.block.size": {'0.21': "mapreduce.jobtracker.jobhistory.block.size", '0.18': "mapred.jobtracker.job.history.block.size"},
    "mapreduce.jobtracker.maxtasks.perjob": {'0.21': "mapreduce.jobtracker.maxtasks.perjob", '0.18': "mapred.jobtracker.maxtasks.per.job"},
    "mapred.jobtracker.maxtasks.per.job": {'0.21': "mapreduce.jobtracker.maxtasks.perjob", '0.18': "mapred.jobtracker.maxtasks.per.job"},
    "mapreduce.jobtracker.restart.recover": {'0.21': "mapreduce.jobtracker.restart.recover", '0.18': "mapred.jobtracker.restart.recover"},
    "mapred.jobtracker.restart.recover": {'0.21': "mapreduce.jobtracker.restart.recover", '0.18': "mapred.jobtracker.restart.recover"},
    "mapreduce.jobtracker.taskscheduler": {'0.21': "mapreduce.jobtracker.taskscheduler", '0.18': "mapred.jobtracker.taskScheduler"},
    "mapred.jobtracker.taskScheduler": {'0.21': "mapreduce.jobtracker.taskscheduler", '0.18': "mapred.jobtracker.taskScheduler"},
    "mapreduce.jobtracker.taskscheduler.taskalloc.capacitypad": {'0.21': "mapreduce.jobtracker.taskscheduler.taskalloc.capacitypad", '0.18': "mapred.jobtracker.taskalloc.capacitypad"},
    "mapred.jobtracker.taskalloc.capacitypad": {'0.21': "mapreduce.jobtracker.taskscheduler.taskalloc.capacitypad", '0.18': "mapred.jobtracker.taskalloc.capacitypad"},
    "mapreduce.join.expr": {'0.21': "mapreduce.join.expr", '0.18': "mapred.join.expr"},
    "mapred.join.expr": {'0.21': "mapreduce.join.expr", '0.18': "mapred.join.expr"},
    "mapreduce.join.keycomparator": {'0.21': "mapreduce.join.keycomparator", '0.18': "mapred.join.keycomparator"},
    "mapred.join.keycomparator": {'0.21': "mapreduce.join.keycomparator", '0.18': "mapred.join.keycomparator"},
    "mapreduce.output.lazyoutputformat.outputformat": {'0.21': "mapreduce.output.lazyoutputformat.outputformat", '0.18': "mapred.lazy.output.format"},
    "mapred.lazy.output.format": {'0.21': "mapreduce.output.lazyoutputformat.outputformat", '0.18': "mapred.lazy.output.format"},
    "mapreduce.input.lineinputformat.linespermap": {'0.21': "mapreduce.input.lineinputformat.linespermap", '0.18': "mapred.line.input.format.linespermap"},
    "mapred.line.input.format.linespermap": {'0.21': "mapreduce.input.lineinputformat.linespermap", '0.18': "mapred.line.input.format.linespermap"},
    "mapreduce.input.linerecordreader.line.maxlength": {'0.21': "mapreduce.input.linerecordreader.line.maxlength", '0.18': "mapred.linerecordreader.maxlength"},
    "mapred.linerecordreader.maxlength": {'0.21': "mapreduce.input.linerecordreader.line.maxlength", '0.18': "mapred.linerecordreader.maxlength"},
    "mapreduce.cluster.local.dir": {'0.21': "mapreduce.cluster.local.dir", '0.18': "mapred.local.dir"},
    "mapred.local.dir": {'0.21': "mapreduce.cluster.local.dir", '0.18': "mapred.local.dir"},
    "mapreduce.tasktracker.local.dir.minspacekill": {'0.21': "mapreduce.tasktracker.local.dir.minspacekill", '0.18': "mapred.local.dir.minspacekill"},
    "mapred.local.dir.minspacekill": {'0.21': "mapreduce.tasktracker.local.dir.minspacekill", '0.18': "mapred.local.dir.minspacekill"},
    "mapreduce.tasktracker.local.dir.minspacestart": {'0.21': "mapreduce.tasktracker.local.dir.minspacestart", '0.18': "mapred.local.dir.minspacestart"},
    "mapred.local.dir.minspacestart": {'0.21': "mapreduce.tasktracker.local.dir.minspacestart", '0.18': "mapred.local.dir.minspacestart"},
    "mapreduce.map.env": {'0.21': "mapreduce.map.env", '0.18': "mapred.map.child.env"},
    "mapred.map.child.env": {'0.21': "mapreduce.map.env", '0.18': "mapred.map.child.env"},
    "mapreduce.map.java.opts": {'0.21': "mapreduce.map.java.opts", '0.18': "mapred.map.child.java.opts"},
    "mapred.map.child.java.opts": {'0.21': "mapreduce.map.java.opts", '0.18': "mapred.map.child.java.opts"},
    "mapreduce.map.log.level": {'0.21': "mapreduce.map.log.level", '0.18': "mapred.map.child.log.level"},
    "mapred.map.child.log.level": {'0.21': "mapreduce.map.log.level", '0.18': "mapred.map.child.log.level"},
    "mapreduce.map.ulimit": {'0.21': "mapreduce.map.ulimit", '0.18': "mapred.map.child.ulimit"},
    "mapred.map.child.ulimit": {'0.21': "mapreduce.map.ulimit", '0.18': "mapred.map.child.ulimit"},
    "mapreduce.map.maxattempts": {'0.21': "mapreduce.map.maxattempts", '0.18': "mapred.map.max.attempts"},
    "mapred.map.max.attempts": {'0.21': "mapreduce.map.maxattempts", '0.18': "mapred.map.max.attempts"},
    "mapreduce.map.output.compress.codec": {'0.21': "mapreduce.map.output.compress.codec", '0.18': "mapred.map.output.compression.codec"},
    "mapred.map.output.compression.codec": {'0.21': "mapreduce.map.output.compress.codec", '0.18': "mapred.map.output.compression.codec"},
    "mapreduce.map.debug.script": {'0.21': "mapreduce.map.debug.script", '0.18': "mapred.map.task.debug.script"},
    "mapred.map.task.debug.script": {'0.21': "mapreduce.map.debug.script", '0.18': "mapred.map.task.debug.script"},
    "mapreduce.job.maps": {'0.21': "mapreduce.job.maps", '0.18': "mapred.map.tasks"},
    "mapred.map.tasks": {'0.21': "mapreduce.job.maps", '0.18': "mapred.map.tasks"},
    "mapreduce.map.speculative": {'0.21': "mapreduce.map.speculative", '0.18': "mapred.map.tasks.speculative.execution"},
    "mapred.map.tasks.speculative.execution": {'0.21': "mapreduce.map.speculative", '0.18': "mapred.map.tasks.speculative.execution"},
    "mapreduce.map.output.key.class": {'0.21': "mapreduce.map.output.key.class", '0.18': "mapred.mapoutput.key.class"},
    "mapred.mapoutput.key.class": {'0.21': "mapreduce.map.output.key.class", '0.18': "mapred.mapoutput.key.class"},
    "mapreduce.map.output.value.class": {'0.21': "mapreduce.map.output.value.class", '0.18': "mapred.mapoutput.value.class"},
    "mapred.mapoutput.value.class": {'0.21': "mapreduce.map.output.value.class", '0.18': "mapred.mapoutput.value.class"},
    "mapreduce.mapper.regex": {'0.21': "mapreduce.mapper.regex", '0.18': "mapred.mapper.regex"},
    "mapred.mapper.regex": {'0.21': "mapreduce.mapper.regex", '0.18': "mapred.mapper.regex"},
    "mapreduce.mapper.regexmapper..group": {'0.21': "mapreduce.mapper.regexmapper..group", '0.18': "mapred.mapper.regex.group"},
    "mapred.mapper.regex.group": {'0.21': "mapreduce.mapper.regexmapper..group", '0.18': "mapred.mapper.regex.group"},
    "mapreduce.map.failures.maxpercent": {'0.21': "mapreduce.map.failures.maxpercent", '0.18': "mapred.max.map.failures.percent"},
    "mapred.max.map.failures.percent": {'0.21': "mapreduce.map.failures.maxpercent", '0.18': "mapred.max.map.failures.percent"},
    "mapreduce.reduce.failures.maxpercent": {'0.21': "mapreduce.reduce.failures.maxpercent", '0.18': "mapred.max.reduce.failures.percent"},
    "mapred.max.reduce.failures.percent": {'0.21': "mapreduce.reduce.failures.maxpercent", '0.18': "mapred.max.reduce.failures.percent"},
    "mapreduce.input.fileinputformat.split.maxsize": {'0.21': "mapreduce.input.fileinputformat.split.maxsize", '0.18': "mapred.max.split.size"},
    "mapred.max.split.size": {'0.21': "mapreduce.input.fileinputformat.split.maxsize", '0.18': "mapred.max.split.size"},
    "mapreduce.jobtracker.tasktracker.maxblacklists": {'0.21': "mapreduce.jobtracker.tasktracker.maxblacklists", '0.18': "mapred.max.tracker.blacklists"},
    "mapred.max.tracker.blacklists": {'0.21': "mapreduce.jobtracker.tasktracker.maxblacklists", '0.18': "mapred.max.tracker.blacklists"},
    "mapreduce.job.maxtaskfailures.per.tracker": {'0.21': "mapreduce.job.maxtaskfailures.per.tracker", '0.18': "mapred.max.tracker.failures"},
    "mapred.max.tracker.failures": {'0.21': "mapreduce.job.maxtaskfailures.per.tracker", '0.18': "mapred.max.tracker.failures"},
    "mapreduce.task.merge.progress.records": {'0.21': "mapreduce.task.merge.progress.records", '0.18': "mapred.merge.recordsBeforeProgress"},
    "mapred.merge.recordsBeforeProgress": {'0.21': "mapreduce.task.merge.progress.records", '0.18': "mapred.merge.recordsBeforeProgress"},
    "mapreduce.input.fileinputformat.split.minsize": {'0.21': "mapreduce.input.fileinputformat.split.minsize", '0.18': "mapred.min.split.size"},
    "mapred.min.split.size": {'0.21': "mapreduce.input.fileinputformat.split.minsize", '0.18': "mapred.min.split.size"},
    "mapreduce.input.fileinputformat.split.minsize.per.node": {'0.21': "mapreduce.input.fileinputformat.split.minsize.per.node", '0.18': "mapred.min.split.size.per.node"},
    "mapred.min.split.size.per.node": {'0.21': "mapreduce.input.fileinputformat.split.minsize.per.node", '0.18': "mapred.min.split.size.per.node"},
    "mapreduce.input.fileinputformat.split.minsize.per.rack": {'0.21': "mapreduce.input.fileinputformat.split.minsize.per.rack", '0.18': "mapred.min.split.size.per.rack"},
    "mapred.min.split.size.per.rack": {'0.21': "mapreduce.input.fileinputformat.split.minsize.per.rack", '0.18': "mapred.min.split.size.per.rack"},
    "mapreduce.output.fileoutputformat.compress": {'0.21': "mapreduce.output.fileoutputformat.compress", '0.18': "mapred.output.compress"},
    "mapred.output.compress": {'0.21': "mapreduce.output.fileoutputformat.compress", '0.18': "mapred.output.compress"},
    "mapreduce.output.fileoutputformat.compress.codec": {'0.21': "mapreduce.output.fileoutputformat.compress.codec", '0.18': "mapred.output.compression.codec"},
    "mapred.output.compression.codec": {'0.21': "mapreduce.output.fileoutputformat.compress.codec", '0.18': "mapred.output.compression.codec"},
    "mapreduce.output.fileoutputformat.compress.type": {'0.21': "mapreduce.output.fileoutputformat.compress.type", '0.18': "mapred.output.compression.type"},
    "mapred.output.compression.type": {'0.21': "mapreduce.output.fileoutputformat.compress.type", '0.18': "mapred.output.compression.type"},
    "mapreduce.output.fileoutputformat.outputdir": {'0.21': "mapreduce.output.fileoutputformat.outputdir", '0.18': "mapred.output.dir"},
    "mapred.output.dir": {'0.21': "mapreduce.output.fileoutputformat.outputdir", '0.18': "mapred.output.dir"},
    "mapreduce.job.output.key.class": {'0.21': "mapreduce.job.output.key.class", '0.18': "mapred.output.key.class"},
    "mapred.output.key.class": {'0.21': "mapreduce.job.output.key.class", '0.18': "mapred.output.key.class"},
    "mapreduce.job.output.key.comparator.class": {'0.21': "mapreduce.job.output.key.comparator.class", '0.18': "mapred.output.key.comparator.class"},
    "mapred.output.key.comparator.class": {'0.21': "mapreduce.job.output.key.comparator.class", '0.18': "mapred.output.key.comparator.class"},
    "mapreduce.job.output.value.class": {'0.21': "mapreduce.job.output.value.class", '0.18': "mapred.output.value.class"},
    "mapred.output.value.class": {'0.21': "mapreduce.job.output.value.class", '0.18': "mapred.output.value.class"},
    "mapreduce.job.output.group.comparator.class": {'0.21': "mapreduce.job.output.group.comparator.class", '0.18': "mapred.output.value.groupfn.class"},
    "mapred.output.value.groupfn.class": {'0.21': "mapreduce.job.output.group.comparator.class", '0.18': "mapred.output.value.groupfn.class"},
    "mapreduce.cluster.permissions.supergroup": {'0.21': "mapreduce.cluster.permissions.supergroup", '0.18': "mapred.permissions.supergroup"},
    "mapred.permissions.supergroup": {'0.21': "mapreduce.cluster.permissions.supergroup", '0.18': "mapred.permissions.supergroup"},
    "mapreduce.pipes.inputformat": {'0.21': "mapreduce.pipes.inputformat", '0.18': "mapred.pipes.user.inputformat"},
    "mapred.pipes.user.inputformat": {'0.21': "mapreduce.pipes.inputformat", '0.18': "mapred.pipes.user.inputformat"},
    "mapreduce.reduce.env": {'0.21': "mapreduce.reduce.env", '0.18': "mapred.reduce.child.env"},
    "mapred.reduce.child.env": {'0.21': "mapreduce.reduce.env", '0.18': "mapred.reduce.child.env"},
    "mapreduce.reduce.java.opts": {'0.21': "mapreduce.reduce.java.opts", '0.18': "mapred.reduce.child.java.opts"},
    "mapred.reduce.child.java.opts": {'0.21': "mapreduce.reduce.java.opts", '0.18': "mapred.reduce.child.java.opts"},
    "mapreduce.reduce.log.level": {'0.21': "mapreduce.reduce.log.level", '0.18': "mapred.reduce.child.log.level"},
    "mapred.reduce.child.log.level": {'0.21': "mapreduce.reduce.log.level", '0.18': "mapred.reduce.child.log.level"},
    "mapreduce.reduce.ulimit": {'0.21': "mapreduce.reduce.ulimit", '0.18': "mapred.reduce.child.ulimit"},
    "mapred.reduce.child.ulimit": {'0.21': "mapreduce.reduce.ulimit", '0.18': "mapred.reduce.child.ulimit"},
    "mapreduce.reduce.maxattempts": {'0.21': "mapreduce.reduce.maxattempts", '0.18': "mapred.reduce.max.attempts"},
    "mapred.reduce.max.attempts": {'0.21': "mapreduce.reduce.maxattempts", '0.18': "mapred.reduce.max.attempts"},
    "mapreduce.reduce.shuffle.parallelcopies": {'0.21': "mapreduce.reduce.shuffle.parallelcopies", '0.18': "mapred.reduce.parallel.copies"},
    "mapred.reduce.parallel.copies": {'0.21': "mapreduce.reduce.shuffle.parallelcopies", '0.18': "mapred.reduce.parallel.copies"},
    "mapreduce.job.reduce.slowstart.completedmaps": {'0.21': "mapreduce.job.reduce.slowstart.completedmaps", '0.18': "mapred.reduce.slowstart.completed.maps"},
    "mapred.reduce.slowstart.completed.maps": {'0.21': "mapreduce.job.reduce.slowstart.completedmaps", '0.18': "mapred.reduce.slowstart.completed.maps"},
    "mapreduce.reduce.debug.script": {'0.21': "mapreduce.reduce.debug.script", '0.18': "mapred.reduce.task.debug.script"},
    "mapred.reduce.task.debug.script": {'0.21': "mapreduce.reduce.debug.script", '0.18': "mapred.reduce.task.debug.script"},
    "mapreduce.job.reduces": {'0.21': "mapreduce.job.reduces", '0.18': "mapred.reduce.tasks"},
    "mapred.reduce.tasks": {'0.21': "mapreduce.job.reduces", '0.18': "mapred.reduce.tasks"},
    "mapreduce.reduce.speculative": {'0.21': "mapreduce.reduce.speculative", '0.18': "mapred.reduce.tasks.speculative.execution"},
    "mapred.reduce.tasks.speculative.execution": {'0.21': "mapreduce.reduce.speculative", '0.18': "mapred.reduce.tasks.speculative.execution"},
    "mapreduce.output.seqbinaryoutputformat.key.class": {'0.21': "mapreduce.output.seqbinaryoutputformat.key.class", '0.18': "mapred.seqbinary.output.key.class"},
    "mapred.seqbinary.output.key.class": {'0.21': "mapreduce.output.seqbinaryoutputformat.key.class", '0.18': "mapred.seqbinary.output.key.class"},
    "mapreduce.output.seqbinaryoutputformat.value.class": {'0.21': "mapreduce.output.seqbinaryoutputformat.value.class", '0.18': "mapred.seqbinary.output.value.class"},
    "mapred.seqbinary.output.value.class": {'0.21': "mapreduce.output.seqbinaryoutputformat.value.class", '0.18': "mapred.seqbinary.output.value.class"},
    "mapreduce.reduce.shuffle.connect.timeout": {'0.21': "mapreduce.reduce.shuffle.connect.timeout", '0.18': "mapred.shuffle.connect.timeout"},
    "mapred.shuffle.connect.timeout": {'0.21': "mapreduce.reduce.shuffle.connect.timeout", '0.18': "mapred.shuffle.connect.timeout"},
    "mapreduce.reduce.shuffle.read.timeout": {'0.21': "mapreduce.reduce.shuffle.read.timeout", '0.18': "mapred.shuffle.read.timeout"},
    "mapred.shuffle.read.timeout": {'0.21': "mapreduce.reduce.shuffle.read.timeout", '0.18': "mapred.shuffle.read.timeout"},
    "mapreduce.task.skip.start.attempts": {'0.21': "mapreduce.task.skip.start.attempts", '0.18': "mapred.skip.attempts.to.start.skipping"},
    "mapred.skip.attempts.to.start.skipping": {'0.21': "mapreduce.task.skip.start.attempts", '0.18': "mapred.skip.attempts.to.start.skipping"},
    "mapreduce.map.skip.proc-count.auto-incr": {'0.21': "mapreduce.map.skip.proc-count.auto-incr", '0.18': "mapred.skip.map.auto.incr.proc.count"},
    "mapred.skip.map.auto.incr.proc.count": {'0.21': "mapreduce.map.skip.proc-count.auto-incr", '0.18': "mapred.skip.map.auto.incr.proc.count"},
    "mapreduce.map.skip.maxrecords": {'0.21': "mapreduce.map.skip.maxrecords", '0.18': "mapred.skip.map.max.skip.records"},
    "mapred.skip.map.max.skip.records": {'0.21': "mapreduce.map.skip.maxrecords", '0.18': "mapred.skip.map.max.skip.records"},
    "mapreduce.job.skiprecords": {'0.21': "mapreduce.job.skiprecords", '0.18': "mapred.skip.on"},
    "mapred.skip.on": {'0.21': "mapreduce.job.skiprecords", '0.18': "mapred.skip.on"},
    "mapreduce.job.skip.outdir": {'0.21': "mapreduce.job.skip.outdir", '0.18': "mapred.skip.out.dir"},
    "mapred.skip.out.dir": {'0.21': "mapreduce.job.skip.outdir", '0.18': "mapred.skip.out.dir"},
    "mapreduce.reduce.skip.proc-count.auto-incr": {'0.21': "mapreduce.reduce.skip.proc-count.auto-incr", '0.18': "mapred.skip.reduce.auto.incr.proc.count"},
    "mapred.skip.reduce.auto.incr.proc.count": {'0.21': "mapreduce.reduce.skip.proc-count.auto-incr", '0.18': "mapred.skip.reduce.auto.incr.proc.count"},
    "mapreduce.reduce.skip.maxgroups": {'0.21': "mapreduce.reduce.skip.maxgroups", '0.18': "mapred.skip.reduce.max.skip.groups"},
    "mapred.skip.reduce.max.skip.groups": {'0.21': "mapreduce.reduce.skip.maxgroups", '0.18': "mapred.skip.reduce.max.skip.groups"},
    "mapreduce.job.speculative.speculativecap": {'0.21': "mapreduce.job.speculative.speculativecap", '0.18': "mapred.speculative.execution.speculativeCap"},
    "mapred.speculative.execution.speculativeCap": {'0.21': "mapreduce.job.speculative.speculativecap", '0.18': "mapred.speculative.execution.speculativeCap"},
    "mapreduce.client.submit.file.replication": {'0.21': "mapreduce.client.submit.file.replication", '0.18': "mapred.submit.replication"},
    "mapred.submit.replication": {'0.21': "mapreduce.client.submit.file.replication", '0.18': "mapred.submit.replication"},
    "mapreduce.jobtracker.system.dir": {'0.21': "mapreduce.jobtracker.system.dir", '0.18': "mapred.system.dir"},
    "mapred.system.dir": {'0.21': "mapreduce.jobtracker.system.dir", '0.18': "mapred.system.dir"},
    "mapreduce.jobtracker.taskcache.levels": {'0.21': "mapreduce.jobtracker.taskcache.levels", '0.18': "mapred.task.cache.levels"},
    "mapred.task.cache.levels": {'0.21': "mapreduce.jobtracker.taskcache.levels", '0.18': "mapred.task.cache.levels"},
    "mapreduce.task.attempt.id": {'0.21': "mapreduce.task.attempt.id", '0.18': "mapred.task.id"},
    "mapred.task.id": {'0.21': "mapreduce.task.attempt.id", '0.18': "mapred.task.id"},
    "mapreduce.task.ismap": {'0.21': "mapreduce.task.ismap", '0.18': "mapred.task.is.map"},
    "mapred.task.is.map": {'0.21': "mapreduce.task.ismap", '0.18': "mapred.task.is.map"},
    "mapreduce.task.partition": {'0.21': "mapreduce.task.partition", '0.18': "mapred.task.partition"},
    "mapred.task.partition": {'0.21': "mapreduce.task.partition", '0.18': "mapred.task.partition"},
    "mapreduce.task.profile": {'0.21': "mapreduce.task.profile", '0.18': "mapred.task.profile"},
    "mapred.task.profile": {'0.21': "mapreduce.task.profile", '0.18': "mapred.task.profile"},
    "mapreduce.task.profile.maps": {'0.21': "mapreduce.task.profile.maps", '0.18': "mapred.task.profile.maps"},
    "mapred.task.profile.maps": {'0.21': "mapreduce.task.profile.maps", '0.18': "mapred.task.profile.maps"},
    "mapreduce.task.profile.params": {'0.21': "mapreduce.task.profile.params", '0.18': "mapred.task.profile.params"},
    "mapred.task.profile.params": {'0.21': "mapreduce.task.profile.params", '0.18': "mapred.task.profile.params"},
    "mapreduce.task.profile.reduces": {'0.21': "mapreduce.task.profile.reduces", '0.18': "mapred.task.profile.reduces"},
    "mapred.task.profile.reduces": {'0.21': "mapreduce.task.profile.reduces", '0.18': "mapred.task.profile.reduces"},
    "mapreduce.task.timeout": {'0.21': "mapreduce.task.timeout", '0.18': "mapred.task.timeout"},
    "mapred.task.timeout": {'0.21': "mapreduce.task.timeout", '0.18': "mapred.task.timeout"},
    "mapreduce.tasktracker.http.address": {'0.21': "mapreduce.tasktracker.http.address", '0.18': "mapred.task.tracker.http.address"},
    "mapred.task.tracker.http.address": {'0.21': "mapreduce.tasktracker.http.address", '0.18': "mapred.task.tracker.http.address"},
    "mapreduce.tasktracker.report.address": {'0.21': "mapreduce.tasktracker.report.address", '0.18': "mapred.task.tracker.report.address"},
    "mapred.task.tracker.report.address": {'0.21': "mapreduce.tasktracker.report.address", '0.18': "mapred.task.tracker.report.address"},
    "mapreduce.tasktracker.taskcontroller": {'0.21': "mapreduce.tasktracker.taskcontroller", '0.18': "mapred.task.tracker.task-controller"},
    "mapred.task.tracker.task-controller": {'0.21': "mapreduce.tasktracker.taskcontroller", '0.18': "mapred.task.tracker.task-controller"},
    "mapreduce.tasktracker.dns.interface": {'0.21': "mapreduce.tasktracker.dns.interface", '0.18': "mapred.tasktracker.dns.interface"},
    "mapred.tasktracker.dns.interface": {'0.21': "mapreduce.tasktracker.dns.interface", '0.18': "mapred.tasktracker.dns.interface"},
    "mapreduce.tasktracker.dns.nameserver": {'0.21': "mapreduce.tasktracker.dns.nameserver", '0.18': "mapred.tasktracker.dns.nameserver"},
    "mapred.tasktracker.dns.nameserver": {'0.21': "mapreduce.tasktracker.dns.nameserver", '0.18': "mapred.tasktracker.dns.nameserver"},
    "mapreduce.tasktracker.events.batchsize": {'0.21': "mapreduce.tasktracker.events.batchsize", '0.18': "mapred.tasktracker.events.batchsize"},
    "mapred.tasktracker.events.batchsize": {'0.21': "mapreduce.tasktracker.events.batchsize", '0.18': "mapred.tasktracker.events.batchsize"},
    "mapreduce.jobtracker.expire.trackers.interval": {'0.21': "mapreduce.jobtracker.expire.trackers.interval", '0.18': "mapred.tasktracker.expiry.interval"},
    "mapred.tasktracker.expiry.interval": {'0.21': "mapreduce.jobtracker.expire.trackers.interval", '0.18': "mapred.tasktracker.expiry.interval"},
    "mapreduce.tasktracker.indexcache.mb": {'0.21': "mapreduce.tasktracker.indexcache.mb", '0.18': "mapred.tasktracker.indexcache.mb"},
    "mapred.tasktracker.indexcache.mb": {'0.21': "mapreduce.tasktracker.indexcache.mb", '0.18': "mapred.tasktracker.indexcache.mb"},
    "mapreduce.tasktracker.instrumentation": {'0.21': "mapreduce.tasktracker.instrumentation", '0.18': "mapred.tasktracker.instrumentation"},
    "mapred.tasktracker.instrumentation": {'0.21': "mapreduce.tasktracker.instrumentation", '0.18': "mapred.tasktracker.instrumentation"},
    "mapreduce.tasktracker.map.tasks.maximum": {'0.21': "mapreduce.tasktracker.map.tasks.maximum", '0.18': "mapred.tasktracker.map.tasks.maximum"},
    "mapred.tasktracker.map.tasks.maximum": {'0.21': "mapreduce.tasktracker.map.tasks.maximum", '0.18': "mapred.tasktracker.map.tasks.maximum"},
    "mapreduce.tasktracker.resourcecalculatorplugin": {'0.21': "mapreduce.tasktracker.resourcecalculatorplugin", '0.18': "mapred.tasktracker.memory_calculator_plugin"},
    "mapred.tasktracker.memory_calculator_plugin": {'0.21': "mapreduce.tasktracker.resourcecalculatorplugin", '0.18': "mapred.tasktracker.memory_calculator_plugin"},
    "mapreduce.tasktracker.resourcecalculatorplugin": {'0.21': "mapreduce.tasktracker.resourcecalculatorplugin", '0.18': "mapred.tasktracker.memorycalculatorplugin"},
    "mapred.tasktracker.memorycalculatorplugin": {'0.21': "mapreduce.tasktracker.resourcecalculatorplugin", '0.18': "mapred.tasktracker.memorycalculatorplugin"},
    "mapreduce.tasktracker.reduce.tasks.maximum": {'0.21': "mapreduce.tasktracker.reduce.tasks.maximum", '0.18': "mapred.tasktracker.reduce.tasks.maximum"},
    "mapred.tasktracker.reduce.tasks.maximum": {'0.21': "mapreduce.tasktracker.reduce.tasks.maximum", '0.18': "mapred.tasktracker.reduce.tasks.maximum"},
    "mapreduce.cluster.temp.dir": {'0.21': "mapreduce.cluster.temp.dir", '0.18': "mapred.temp.dir"},
    "mapred.temp.dir": {'0.21': "mapreduce.cluster.temp.dir", '0.18': "mapred.temp.dir"},
    "mapreduce.partition.keycomparator.options": {'0.21': "mapreduce.partition.keycomparator.options", '0.18': "mapred.text.key.comparator.options"},
    "mapred.text.key.comparator.options": {'0.21': "mapreduce.partition.keycomparator.options", '0.18': "mapred.text.key.comparator.options"},
    "mapreduce.partition.keypartitioner.options": {'0.21': "mapreduce.partition.keypartitioner.options", '0.18': "mapred.text.key.partitioner.options"},
    "mapred.text.key.partitioner.options": {'0.21': "mapreduce.partition.keypartitioner.options", '0.18': "mapred.text.key.partitioner.options"},
    "mapreduce.output.textoutputformat.separator": {'0.21': "mapreduce.output.textoutputformat.separator", '0.18': "mapred.textoutputformat.separator"},
    "mapred.textoutputformat.separator": {'0.21': "mapreduce.output.textoutputformat.separator", '0.18': "mapred.textoutputformat.separator"},
    "mapreduce.task.id": {'0.21': "mapreduce.task.id", '0.18': "mapred.tip.id"},
    "mapred.tip.id": {'0.21': "mapreduce.task.id", '0.18': "mapred.tip.id"},
    "mapreduce.client.genericoptionsparser.used": {'0.21': "mapreduce.client.genericoptionsparser.used", '0.18': "mapred.used.genericoptionsparser"},
    "mapred.used.genericoptionsparser": {'0.21': "mapreduce.client.genericoptionsparser.used", '0.18': "mapred.used.genericoptionsparser"},
    "mapreduce.task.userlog.limit.kb": {'0.21': "mapreduce.task.userlog.limit.kb", '0.18': "mapred.userlog.limit.kb"},
    "mapred.userlog.limit.kb": {'0.21': "mapreduce.task.userlog.limit.kb", '0.18': "mapred.userlog.limit.kb"},
    "mapreduce.job.userlog.retain.hours": {'0.21': "mapreduce.job.userlog.retain.hours", '0.18': "mapred.userlog.retain.hours"},
    "mapred.userlog.retain.hours": {'0.21': "mapreduce.job.userlog.retain.hours", '0.18': "mapred.userlog.retain.hours"},
    "mapreduce.task.output.dir": {'0.21': "mapreduce.task.output.dir", '0.18': "mapred.work.output.dir"},
    "mapred.work.output.dir": {'0.21': "mapreduce.task.output.dir", '0.18': "mapred.work.output.dir"},
    "mapreduce.job.working.dir": {'0.21': "mapreduce.job.working.dir", '0.18': "mapred.working.dir"},
    "mapred.working.dir": {'0.21': "mapreduce.job.working.dir", '0.18': "mapred.working.dir"},
    "mapreduce.job.combine.class": {'0.21': "mapreduce.job.combine.class", '0.18': "mapreduce.combine.class"},
    "mapreduce.combine.class": {'0.21': "mapreduce.job.combine.class", '0.18': "mapreduce.combine.class"},
    "mapreduce.job.inputformat.class": {'0.21': "mapreduce.job.inputformat.class", '0.18': "mapreduce.inputformat.class"},
    "mapreduce.inputformat.class": {'0.21': "mapreduce.job.inputformat.class", '0.18': "mapreduce.inputformat.class"},
    "mapreduce.cluster.permissions.supergroup": {'0.21': "mapreduce.cluster.permissions.supergroup", '0.18': "mapreduce.jobtracker.permissions.supergroup"},
    "mapreduce.jobtracker.permissions.supergroup": {'0.21': "mapreduce.cluster.permissions.supergroup", '0.18': "mapreduce.jobtracker.permissions.supergroup"},
    "mapreduce.job.map.class": {'0.21': "mapreduce.job.map.class", '0.18': "mapreduce.map.class"},
    "mapreduce.map.class": {'0.21': "mapreduce.job.map.class", '0.18': "mapreduce.map.class"},
    "mapreduce.job.outputformat.class": {'0.21': "mapreduce.job.outputformat.class", '0.18': "mapreduce.outputformat.class"},
    "mapreduce.outputformat.class": {'0.21': "mapreduce.job.outputformat.class", '0.18': "mapreduce.outputformat.class"},
    "mapreduce.job.partitioner.class": {'0.21': "mapreduce.job.partitioner.class", '0.18': "mapreduce.partitioner.class"},
    "mapreduce.partitioner.class": {'0.21': "mapreduce.job.partitioner.class", '0.18': "mapreduce.partitioner.class"},
    "mapreduce.job.reduce.class": {'0.21': "mapreduce.job.reduce.class", '0.18': "mapreduce.reduce.class"},
    "mapreduce.reduce.class": {'0.21': "mapreduce.job.reduce.class", '0.18': "mapreduce.reduce.class"},
    "mapreduce.map.combine.minspills": {'0.21': "mapreduce.map.combine.minspills", '0.18': "min.num.spills.for.combine"},
    "min.num.spills.for.combine": {'0.21': "mapreduce.map.combine.minspills", '0.18': "min.num.spills.for.combine"},
    "mapreduce.fieldsel.reduce.output.key.value.fields.spec": {'0.21': "mapreduce.fieldsel.reduce.output.key.value.fields.spec", '0.18': "reduce.output.key.value.fields.spec"},
    "reduce.output.key.value.fields.spec": {'0.21': "mapreduce.fieldsel.reduce.output.key.value.fields.spec", '0.18': "reduce.output.key.value.fields.spec"},
    "mapreduce.input.sequencefileinputfilter.class": {'0.21': "mapreduce.input.sequencefileinputfilter.class", '0.18': "sequencefile.filter.class"},
    "sequencefile.filter.class": {'0.21': "mapreduce.input.sequencefileinputfilter.class", '0.18': "sequencefile.filter.class"},
    "mapreduce.input.sequencefileinputfilter.frequency": {'0.21': "mapreduce.input.sequencefileinputfilter.frequency", '0.18': "sequencefile.filter.frequency"},
    "sequencefile.filter.frequency": {'0.21': "mapreduce.input.sequencefileinputfilter.frequency", '0.18': "sequencefile.filter.frequency"},
    "mapreduce.input.sequencefileinputfilter.regex": {'0.21': "mapreduce.input.sequencefileinputfilter.regex", '0.18': "sequencefile.filter.regex"},
    "sequencefile.filter.regex": {'0.21': "mapreduce.input.sequencefileinputfilter.regex", '0.18': "sequencefile.filter.regex"},
    "mapreduce.tasktracker.host.name": {'0.21': "mapreduce.tasktracker.host.name", '0.18': "slave.host.name"},
    "slave.host.name": {'0.21': "mapreduce.tasktracker.host.name", '0.18': "slave.host.name"},
    "mapreduce.tasktracker.contention.tracking": {'0.21': "mapreduce.tasktracker.contention.tracking", '0.18': "tasktracker.contention.tracking"},
    "tasktracker.contention.tracking": {'0.21': "mapreduce.tasktracker.contention.tracking", '0.18': "tasktracker.contention.tracking"},
    "mapreduce.tasktracker.http.threads": {'0.21': "mapreduce.tasktracker.http.threads", '0.18': "tasktracker.http.threads"},
    "tasktracker.http.threads": {'0.21': "mapreduce.tasktracker.http.threads", '0.18': "tasktracker.http.threads"},
    "mapreduce.job.user.name": {'0.21': "mapreduce.job.user.name", '0.18': "user.name"},
    "user.name": {'0.21': "mapreduce.job.user.name", '0.18': "user.name"},
}

def translate_jobconf(variable):
    """ Translates a jobconf variable into the equivalent name in 
        other versions of hadoop. 
        Returns an iterator over the list of equivalent arguements
    """
    return jobconf_map[variable].itervalues()


def translate_jobconf_to_version(variable, version):
    """ Translates a jobconf variable into the equivalent name in 
        the given version of hadoop.
    """
    return jobconf_map[variable][version]
    

def get_jobconf_value(variable):
    """gets a jobconf varaible from runtime environment
    """
    name = variable.replace('.','_')
    if name in os.environ:
        return os.environ[name]

    # try alternatives
    for var in translate_jobconf(variable):
        var = dots_to_underscores(var)
        if var in os.environ:
            return os.environ[var]

    raise KeyError("%s jobconf variable not found" % variable)
